version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # volumes:
      # - ./backend:/app  # Mount code for hot-reloading

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Serve React on port 3000
    depends_on:
      - backend
    # volumes:
      # - ./frontend:/app  # Mount code for hot-reloading
